PROJECT = rest_hello_world
PROJECT_DESCRIPTION = Cowboy REST Hello World example
PROJECT_VERSION = 1

DEPS = cowboy jiffy
dep_cowboy_commit = master
dep_jiffy = git "https://github.com/davisp/jiffy.git" 

REL_DEPS = relx 


include ../../erlang.mk
